# Generated by Django 2.1.3 on 2018-11-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('real_account', models.BooleanField()),
                ('account_type', models.IntegerField()),
                ('default_profile_pic', models.IntegerField()),
                ('no_name', models.IntegerField()),
                ('no_desc', models.IntegerField()),
                ('lt_30_friends', models.IntegerField()),
                ('gt_1000_friends', models.IntegerField()),
                ('not_geo_located', models.IntegerField()),
                ('three_friends_one_followers', models.IntegerField()),
                ('never_tweeted', models.IntegerField()),
            ],
        ),
    ]
