# Generated by Django 2.1.3 on 2018-11-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterstruth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
