# Generated by Django 2.1.3 on 2019-02-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterstruth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='account_id',
            new_name='account',
        ),
    ]
