# Generated by Django 2.1.3 on 2019-02-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterstruth', '0002_auto_20190204_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='lev_distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
