# Generated by Django 2.1.3 on 2019-02-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('real_account', models.BooleanField()),
                ('account_type', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('screen_name', models.CharField(max_length=16)),
                ('statuses_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('favourites_count', models.IntegerField()),
                ('listed_count', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=25)),
                ('time_zone', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=70)),
                ('default_profile', models.IntegerField()),
                ('default_profile_image', models.IntegerField()),
                ('geo_enabled', models.IntegerField()),
                ('profile_image_url', models.CharField(max_length=240)),
                ('profile_image_url_https', models.CharField(max_length=240)),
                ('profile_banner_url', models.CharField(max_length=100)),
                ('profile_use_background_image', models.IntegerField()),
                ('profile_background_image_url', models.CharField(max_length=240)),
                ('profile_background_image_url_https', models.CharField(max_length=240)),
                ('profile_background_tile', models.IntegerField()),
                ('utc_offset', models.IntegerField()),
                ('protected', models.IntegerField()),
                ('verified', models.IntegerField()),
                ('description', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('in_reply_to_status_id', models.BigIntegerField()),
                ('in_reply_to_user_id', models.BigIntegerField()),
                ('in_reply_to_screen_name', models.CharField(max_length=30)),
                ('retweeted_status_id', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('retweet_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('possibly_sensitive', models.IntegerField()),
                ('num_hashtags', models.IntegerField()),
                ('num_urls', models.IntegerField()),
                ('num_mentions', models.IntegerField()),
                ('timestamp', models.CharField(max_length=60)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterstruth.Account')),
            ],
        ),
    ]
